PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVC_PruebaTecnica.Models
{
    public class Producto
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Tipo { get; set; }
        public int CantidadActual { get; set; }
        public int CantidadPedido { get; set; }
        public int CantidadVendida { get; set; }
        public decimal PrecioVenta { get; set; }
    }
}

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_PruebaTecnica.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Controllers/ProductosController.cs
using MVC_PruebaTecnica.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVC_PruebaTecnica.Controllers
{
    public class ProductosController : Controller
    {
        // GET: Productos
        private const string CacheKey = "ProductosCache";

        public List<Producto> productos;

        // Acción para mostrar la lista de productos
        public ActionResult Index()
        {

            if (HttpContext.Cache[CacheKey] != null)
            {
                productos = (List<Producto>)HttpContext.Cache[CacheKey];
            }
            else
            {
                // Obtener productos de la base de datos
                productos = new List<Producto>
                {
                    new Producto { Id = 1, Nombre = "Producto1", Tipo = "Tipo1", CantidadActual = 10, CantidadPedido = 5, CantidadVendida = 0,PrecioVenta = 10.5m },
                    // Agrega los demás productos aquí
                    new Producto { Id = 2, Nombre = "Producto2", Tipo = "Tipo2", CantidadActual = 10, CantidadPedido = 5, CantidadVendida = 0,PrecioVenta = 10.5m },
                };

                HttpContext.Cache[CacheKey] = productos; // Almacenar productos en la caché
            }

            return View(productos);
        }

        // Acción para vender unidades de un producto
        public ActionResult Vender(int id, int cantidad)
        {
            List<Producto> productos = (List<Producto>)HttpContext.Cache[CacheKey];
            Producto producto = productos.FirstOrDefault(p => p.Id == id);

            if (producto != null)
            {
                // Realizar la venta y restar la cantidad vendida
                producto.CantidadActual -= cantidad;

                // Realizar la venta y restar la cantidad vendida
                producto.CantidadVendida += cantidad;

                // Actualizar la entrada de la caché
                HttpContext.Cache[CacheKey] = productos;
            }

            return RedirectToAction("Index");
        }


        // Acción para hacer un pedido de un producto
        public ActionResult HacerPedido(int id, int cantidad)
        {
            List<Producto> productos = (List<Producto>)HttpContext.Cache[CacheKey];
            Producto producto = productos.FirstOrDefault(p => p.Id == id);

            if (producto != null)
            {
                // Realizar el pedido y agregar la cantidad solicitada
                producto.CantidadActual += cantidad;

                // Actualizar la entrada de la caché
                HttpContext.Cache[CacheKey] = productos;
            }

            return RedirectToAction("Index");

        }


        /// <summary>
        /// Acción para ver el producto más vendido
        /// </summary>
        /// <returns></returns>
        public ActionResult MasVendido()
        {
            List<Producto> productos = (List<Producto>)HttpContext.Cache[CacheKey];

            Producto productoMasVendido = productos.OrderByDescending(p => p.CantidadVendida).FirstOrDefault();

            return View(productoMasVendido);
        }

        /// <summary>
        /// Acción para ver el producto menos vendido
        /// </summary>
        /// <returns></returns>
        public ActionResult MenosVendido()
        {
            List<Producto> productos = (List<Producto>)HttpContext.Cache[CacheKey];

            Producto productoMenosVendido = productos.OrderBy(p => p.CantidadVendida).FirstOrDefault();

            return View(productoMenosVendido);
        }

        /// <summary>
        /// Acción para ver el total de ventas
        /// </summary>
        /// <returns></returns>
        public ActionResult TotalVentas()
        {
            List<Producto> productos = (List<Producto>)HttpContext.Cache[CacheKey];

            decimal totalVentas = productos.Sum(p => p.CantidadVendida * p.PrecioVenta);

            ViewBag.TotalVentas = totalVentas;

            return View();
        }
    }
}

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Productos/HacerPedido.cshtml
@model MVC_PruebaTecnica.Models.Producto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>HacerPedido</title>
</head>
<body>
    <h2>Hacer Pedido</h2>

    @using (Html.BeginForm("HacerPedido", "Productos"))
    {
        <label>Producto: @Model.Nombre</label>
        <br />
        <label>Cantidad:</label>
        @Html.TextBox("cantidad")
        <br />
        <input type="hidden" name="id" value="@Model.Id" />
        <input type="submit" value="Hacer Pedido" />
    }
</body>
</html>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Productos/Index.cshtml
@model List<MVC_PruebaTecnica.Models.Producto>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<!DOCTYPE html>
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>




<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>


    <h2>Listado de Productos</h2>

    <table class="table table-bordered">
        <thead>

            <tr>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Cantidad Actual</th>

                <th>Cantidad Vendida</th>
                <th>Precio Venta</th>
                <th>Vender</th> <!-- Columna adicional para los botones -->
                <th>Hacer Pedido</th> <!-- Columna adicional para los botones -->
            </tr>
        </thead>
        <tbody>
            @foreach (var producto in Model)
            {
                <tr>
                    <td>@producto.Nombre</td>
                    <td>@producto.Tipo</td>
                    <td>@producto.CantidadActual</td>

                    <td>@producto.CantidadVendida</td>
                    <td>@producto.PrecioVenta</td>
                    <td>
                        @using (Html.BeginForm("Vender", "Productos", FormMethod.Post))
                        {
                            @Html.Hidden("id", producto.Id)
                            @Html.TextBox("cantidad")
                            <input type="submit" value="Vender" class="btn btn-primary" />
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("HacerPedido", "Productos", FormMethod.Post))
                        {
                            @Html.Hidden("id", producto.Id)
                            @Html.TextBox("cantidad")
                            <input type="submit" value="Hacer Pedido" class="btn btn-success" />
                        }
                    </td>
                </tr>
            }
        </tbody>


    </table>


</body>
</html>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Productos/MasVendido.cshtml
@model MVC_PruebaTecnica.Models.Producto
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<!DOCTYPE html>
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MasVendido</title>
</head>
<body>
    <h2>Producto Más Vendido</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Cantidad Vendida</th>
                    </tr>
                    <tr>
                        <td>@Model.Nombre</td>
                        <td>@Model.Tipo</td>
                        <td>@Model.CantidadVendida</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

</body>
</html>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Productos/MenosVendido.cshtml
@model MVC_PruebaTecnica.Models.Producto
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<!DOCTYPE html>
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>MenosVendido</title>
</head>
<body>
    <h2>Producto Menos Vendido</h2>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered">
                    <tr>
                        <th>Nombre</th>
                        <th>Tipo</th>
                        <th>Cantidad Vendida</th>
                    </tr>
                    <tr>
                        <td>@Model.Nombre</td>
                        <td>@Model.Tipo</td>
                        <td>@Model.CantidadVendida</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

</body>
</html>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Productos/TotalVentas.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<!DOCTYPE html>
<link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TotalVentas</title>
</head>
<body>

    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="alert alert-success">
                    <h4>Total de Ventas:</h4>
                    <p>@ViewBag.TotalVentas</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Productos/Vender.cshtml
@model MVC_PruebaTecnica.Models.Producto
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Vender</title>
</head>
<body>

    <h2>Vender Producto</h2>

    @using (Html.BeginForm("Vender", "Productos"))
    {
        <label>Producto: @Model.Nombre</label>
        <br />
        <label>Cantidad:</label>
        @Html.TextBox("cantidad")
        <br />
        <input type="hidden" name="id" value="@Model.Id" />
        <input type="submit" value="Vender" />
    }

</body>
</html>

PruebaTecnica_Desarrollo/MVC_PruebaTecnica/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Inventario", "Index", "Productos", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Producto más vendido", "MasVendido", "Productos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Producto menos Vendido", "MenosVendido", "Productos", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Total Ventas", "TotalVentas", "Productos", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>